# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 22:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0002_auto_20160812_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('bookManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('reviewManger', django.db.models.manager.Manager()),
            ],
        ),
    ]
